swagger: '2.0'
info:
  version: 1.0.0
  title: Hilbert API
  description: Docs for using the Hilbert system
paths:
  /auth/register:
    post:
      description: Create a new account
      parameters:
        - name: register
          in: body
          description: creates a new account in our database
          schema:
            type: object
            required:
              - username
              - email
              - password
              - firstname
              - lastname
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
              firstname:
                type: string
              lastname:
                type: string
      responses:
        201:
          description: Account successfully created
          schema:
            type: object
            properties:
              token:
                type: string
              user:
                $ref: '#/models/User'
        400:
          description: Bad Request
  /auth/login:
    post:
      description: Login to an existing account
      parameters:
        - name: register
          in: body
          description: username and password
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: Login successfully
          schema:
            type: object
            properties:
              token:
                type: string
              user:
                $ref: '#/models/User'
        400:
          description: Incorrect username or password.
  /auth/ping:
    get:
      description: test authentication
      responses:
        200:
          description: successfully authenticate
          schema:
            $ref: '#/models/User'
        401:
          description: authentication failed

models:
  User:
    required:
      - id
      - username
      - email
      - firstname
      - lastname
    properties:
      id:
        type: string
      username:
        type: string
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      phone:
        type: string
      address:
        type: string
