language: node.js
node_js:
- "node"

sudo: required

cache: yarn

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0 -export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn

services: 
- docker

script:
- yarn test
- docker build -t hilbert-backend .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker tag hilbert-backend $DOCKER_USER/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER
- docker push $DOCKER_USER/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER
- docker tag hilbert-backend $DOCKER_USER/hilbert-backend:latest
- docker push $DOCKER_USER/hilbert-backend:latest