language: node_js
node_js:
        - "node"

cache: yarn

before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0 -export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn

services: 
        - docker

stages:
        - name: run test
          if: type = pull_request
        
        - name: docker build to docker hub
          if: NOT type = push AND NOT type = pull_request
        

jobs:
        include:
                - stage: run test
                  script: 
                        - yarn test
                
                - stage: docker build to docker hub
                  script:
                        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
                        - docker build -t hilbert-backend .
                        
                        - if [ $TRAVIS_BRANCH == "dev" ] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER && 
                                docker push $DOCKER_USER/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER ; fi
                        
                        - if [ $TRAVIS_BRANCH == "master" ] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:prod-$TRAVIS_BUILD_NUMBER && 
                                docker push $DOCKER_USER/hilbert-backend:prod-$TRAVIS_BUILD_NUMBER ; fi
                        
                        - if [ $TRAVIS_BRANCH == "feat/reservation" ] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:feat/reservation-$TRAVIS_BUILD_NUMBER && 
                                docker push $DOCKER_USER/hilbert-backend:feat/reservation-$TRAVIS_BUILD_NUMBER ; fi
                        
                        - docker tag hilbert-backend $DOCKER_USER/hilbert-backend:latest
                        - docker push $DOCKER_USER/hilbert-backend:latest
                
                  

