language: node.js
node_js:
- "node"

sudo: required

cache: yarn

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0 -export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn

services: 
- docker
script:
- if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] ; then yarn test  ; fi
- docker build -t hilbert-backend .

after_success:
- docker login -u "prime47457" -p "99999prime"
- if [[ $TRAVIS_PULL_REQUEST_BRANCH == "dev" ]] ; then docker tag hilbert-backend prime47457/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER && 
        docker push prime47457/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER ; fi
- if [[ $TRAVIS_PULL_REQUEST_BRANCH == "master" ]] ; then docker tag hilbert-backend prime47457/hilbert-backend:prod-$TRAVIS_BUILD_NUMBER && 
        docker push prime47457/hilbert-backend:prod-$TRAVIS_BUILD_NUMBER ; fi
- if [[ $TRAVIS_PULL_REQUEST_BRANCH == "feat/reservation" ]] ; then docker tag hilbert-backend prime47457/hilbert-backend:feat/reservation-$TRAVIS_BUILD_NUMBER && 
        docker push prime47457/hilbert-backend:feat/reservation-$TRAVIS_BUILD_NUMBER ; fi
- docker tag hilbert-backend prime47457/hilbert-backend:latest
- docker push prime47457/hilbert-backend:latest