language: node.js
node_js:
- "node"

cache: yarn

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0 -export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn

services: 
- docker

script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi' 
- yarn test