language: node.js
node_js:
- "node"

sudo: required

cache: yarn

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0 -export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn

services: 
- docker
script:
- if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] ; then yarn test  ; fi
- docker build -t hilbert-backend .

after_success:
        if: $TRAVIS_EVENT_TYPE != "pull_request" 
                docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
<<<<<<< HEAD
                if [[ $TRAVIS_BRANCH == "dev" ]] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER && 
                        docker push $DOCKER_USER/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER ; fi
                if [[ $TRAVIS_BRANCH == "master" ]] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:prod-$TRAVIS_BUILD_NUMBER && 
                        docker push $DOCKER_USER/hilbert-backend:prod-$TRAVIS_BUILD_NUMBER ; fi
                if [[ $TRAVIS_BRANCH == "feat/reservation" ]] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:feat/reservation-$TRAVIS_BUILD_NUMBER && 
=======
                if [[ branch == "dev" ]] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER && 
                        docker push $DOCKER_USER/hilbert-backend:dev-$TRAVIS_BUILD_NUMBER ; fi
                if [[ branch == "master" ]] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:prod-$TRAVIS_BUILD_NUMBER && 
                        docker push $DOCKER_USER/hilbert-backend:prod-$TRAVIS_BUILD_NUMBER ; fi
                if [[ branch == "feat/reservation" ]] ; then docker tag hilbert-backend $DOCKER_USER/hilbert-backend:feat/reservation-$TRAVIS_BUILD_NUMBER && 
>>>>>>> dev
                        docker push $DOCKER_USER/hilbert-backend:feat/reservation-$TRAVIS_BUILD_NUMBER ; fi
                docker tag hilbert-backend $DOCKER_USER/hilbert-backend:latest
                docker push $DOCKER_USER/hilbert-backend:latest
