version: "3.2"

services:
  backend:
    build:
      context: ./
    container_name: hilbert-backend
    environment:
      PORT:
      SECRET:
      DB_URI:
      DB:
      NODE_ENV:
      MQTT_HOST:
      MQTT_PORT:
      MQTT_USERNAME:
      MQTT_PASSWORD:
      MAILER_USER:
      MAILER_CLIENT_ID:
      MAILER_CLIENT_SECRET:
      MAILER_REFRESH_TOKEN:
